//This project was uploaded by WeehWooh on GitHub// Slow Dancing in the Dark by Joji //
void setup ()
{
  
  //Variable Chart\\
  
  int pin = 12;
  int thirtysecond = 52.817;
  int sixteenth = 105.634;
  int eighth = 211.268;
  int doteighth = eighth + sixteenth;
  int quarter = 422.535;
  int dotquarter = 633.803;
  int triplet = 281.69;
  int half = 845.07;
  int dothalf = 1267.605;
  int whole = 1690.14;
  int rest = 150;
  int c0 = 16;
  int csharp0 = 17;
  int dflat0 = 17;
  int d0 = 18;
  int dsharp0 = 19;
  int eflat0 = 19;
  int e0 = 21;
  int f0 = 22;
  int fsharp0 = 23;
  int gflat0 = 23;
  int g0 = 25;
  int gsharp0 = 26;
  int aflat0 = 26;
  int a0 = 28;
  int asharp0 = 29;
  int bflat0 = 29;
  int b0 = 31;
  int c1 = 33;
  int csharp1 = 35;
  int dflat1 = 35;
  int d1 = 37;
  int dsharp1 = 39;
  int eflat1 = 39;
  int e1 = 41;
  int f1 = 44;
  int fsharp1 = 46;
  int gflat1 = 46;
  int g1 = 49;
  int gsharp1 = 52;
  int aflat1 = 52;
  int a1 = 55;
  int asharp1 = 58;
  int bflat1 = 58;
  int b1 = 62;
  int c2 = 65;
  int csharp2 = 69;
  int dflat2 = 69;
  int d2 = 73;
  int dsharp2 = 78;
  int eflat2 = 78;
  int e2 = 82;
  int f2 = 87;
  int fsharp2 = 93;
  int gflat2 = 93;
  int g2 = 98;
  int gsharp2 = 104;
  int aflat2 = 104;
  int a2 = 110;
  int asharp2 = 117;
  int bflat2 = 117;
  int b2 = 124;
  int c3 = 131;
  int csharp3 = 139;
  int dflat3 = 139;
  int d3 = 147;
  int dsharp3 = 156;
  int eflat3 = 156;
  int e3 = 165;
  int f3 = 175;
  int fsharp3 = 185;
  int gflat3 = 185;
  int g3 = 196;
  int gsharp3 = 208;
  int aflat3 = 208;
  int a3 = 220;
  int asharp3 = 233;
  int bflat3 = 233;
  int b3 = 247;
  int c4 = 262;
  int csharp4 = 277;
  int dflat4 = 277;
  int d4 = 294;
  int dsharp4 = 311;
  int eflat4 = 311;
  int e4 = 330;
  int f4 = 349;
  int fsharp4 = 370;
  int gflat4 = 370;
  int g4 = 392;
  int gsharp4 = 415;
  int aflat4 = 415;
  int a4 = 440;
  int asharp4 = 466;
  int bflat4 = 466;
  int b4 = 494;
  int c5 = 523;
  int csharp5 = 554;
  int dflat5 = 554;
  int d5 = 587;
  int dsharp5 = 622;
  int eflat5 = 622;
  int e5 = 659;
  int f5 = 699;
  int fsharp5 = 740;
  int gflat5 = 740;
  int g5 = 784;
  int gsharp5 = 831;
  int aflat5 = 831;
  int a5 = 880;
  int asharp5 = 932;
  int bflat5 = 932;
  int b5 =988;
  int c6 = 1047;
  int csharp6 = 1109;
  int dflat6 = 1109;
  int d6 = 1175;
  int dsharp6 = 1245;
  int eflat6 = 1245;
  int e6 = 1319;
  int f6 = 1397;
  int fsharp6 = 1480;
  int gflat6 = 1480;
  int g6 = 1568;
  int gsharp6 = 1661;
  int aflat6 = 1661;
  int a6 = 1760;
  int asharp6 = 1865;
  int bflat6 = 1865;
  int b6 =1976;
  int c7 = 2093;
  int csharp7 = 2217;
  int dflat7 = 2217;
  int d7 = 2349;
  int dsharp7 = 2489;
  int eflat7 = 2489;
  int e7 = 2637;
  int f7 = 2794;
  int fsharp7 = 2960;
  int gflat7 = 2960;
  int g7 = 3136;
  int gsharp7 = 3322;
  int aflat7 = 3322;
  int a7 = 3520;
  int asharp7 = 3729;
  int bflat7 = 3729;
  int b7 = 3951;
  int c8 = 4186;
  int csharp8 = 4435;
  int dflat8 = 4435;
  int d8 = 4699;
  int dsharp8 = 4978;
  int eflat8 =4978; 
  int e8 = 5274;
  int f8 = 5588;
  int fsharp8 = 5920;
  int gflat8 = 5920;
  int g8 = 6272;
  int gsharp8 = 6645;
  int aflat8 = 6645;
  int a8 = 7040;
  int asharp8 = 7459;
  int bflat8 = 7459;
  int b8 =7902;

  //Song Begins//
  tone (pin, g5);
  delay (eighth);
  noTone (pin);
tone (pin, f5);
  delay (eighth);
  noTone (pin);
tone (pin, g5);
  delay (eighth);
  noTone (pin);
tone (pin, f5);
  delay (eighth);
  noTone (pin);
tone (pin, g5);
  delay (whole);
  noTone (pin);
  tone (pin, rest);
  delay (quarter);
  noTone (pin);
  tone (pin, rest);
  delay (eighth);
  noTone (pin);
  tone (pin, eflat4);
  delay (quarter);
  noTone (pin);
  tone (pin, g5);
  delay (eighth);
  noTone (pin);
  tone (pin, bflat5);
  delay (half);
  noTone (pin);
  tone (pin, d5);
  delay (eighth + quarter);
  noTone (pin);
tone (pin, bflat5);
  delay (eighth);
  noTone (pin);
  tone (pin, bflat5);
  delay (quarter + whole);
  noTone (pin);
  tone (pin, bflat5);
  delay (eighth);
  noTone (pin);
  tone (pin, aflat5);
  delay (eighth);
  noTone (pin);
  tone (pin, g4);
  delay (eighth);
  noTone (pin);
  tone (pin, f4);
  delay (quarter);
  noTone (pin);
  tone (pin, g4);
  delay (eighth + dothalf + half);
  noTone (pin);
  tone (pin, bflat5);
  delay (eighth);
  noTone (pin);
  tone (pin, aflat5);
  delay (eighth);
  noTone (pin);
  tone (pin, g4);
  delay (eighth);
  noTone (pin);
  tone (pin, f4);
  delay (quarter + whole);
  noTone (pin);
  tone (pin, f4);
  delay (whole);
  noTone (pin);
  tone (pin, rest);
  delay (half + quarter + eighth);
  noTone (pin);
  tone (pin, eflat4);
  delay (eighth);
  noTone (pin);
  tone (pin, c5);
  delay (dotquarter);
  noTone (pin);
  tone (pin, bflat5);
  delay (eighth);
  noTone (pin);
  tone (pin, aflat5);
  delay (dotquarter);
  noTone (pin);
  tone (pin, aflat5);
  delay (eighth);
  noTone (pin);
  tone (pin, aflat5);
  delay (dotquarter);
  noTone (pin);
  tone (pin, g4);
  delay (eighth);
  noTone (pin);
  tone (pin, g4);
  delay (dotquarter);
  noTone (pin);
  tone (pin, aflat5);
  delay (eighth);
  noTone (pin);
  tone (pin, aflat5);
  delay (quarter);
  noTone (pin);
  tone (pin, g4);
  delay (half);
  noTone (pin);
  tone (pin, rest);
  delay (quarter);
  noTone (pin);
  tone (pin, eflat4);
  delay (eighth);
  noTone (pin);
  tone (pin, c5);
  delay (dotquarter);
  noTone (pin);
  tone (pin, bflat5);
  delay (eighth);
  noTone (pin);
  tone (pin, aflat5);
  delay (dotquarter);
  noTone (pin);
  tone (pin, aflat5);
  delay (eighth);
  noTone (pin);
  tone (pin, aflat5);
  delay (dotquarter);
  noTone (pin);
  tone (pin, g4);
  delay (eighth);
  noTone (pin);
  tone (pin, g4);
  delay (dotquarter);
  noTone (pin);
  tone (pin, aflat5);
  delay (eighth);
  noTone (pin);
  tone (pin, aflat5);
  delay (quarter);
  noTone (pin);
  tone (pin, gsharp4);
  delay (half);
  noTone (pin);
  tone (pin, rest);
  delay (quarter + eighth);
  noTone (pin);
  tone (pin, eflat4);
  delay (eighth);
  noTone (pin);
  tone (pin, eflat4);
  delay (eighth);
  noTone (pin);
  tone (pin, eflat4);
  delay (eighth);
  noTone (pin);
  tone (pin, eflat4);
  delay (eighth);
  noTone (pin);
  tone (pin, f4);
  delay (eighth + sixteenth);
  noTone (pin);
  tone (pin, f4);
  delay (quarter);
  noTone (pin);
    tone (pin, rest);
  delay (quarter + eighth);
  noTone (pin);
  tone (pin, eflat4);
  delay (eighth);
  noTone (pin);
  tone (pin, eflat4);
  delay (eighth);
  noTone (pin);
  tone (pin, eflat4);
  delay (eighth);
  noTone (pin);
  tone (pin, eflat4);
  delay (eighth);
  noTone (pin);
  tone (pin, f4);
  delay (eighth + sixteenth);
  noTone (pin);
  tone (pin, f4);
  delay (quarter);
  noTone (pin);
  tone (pin, rest);
  delay (quarter + eighth);
  noTone (pin);
   tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, rest);
  delay (quarter + half + eighth);
  noTone (pin);
   tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, rest);
  delay (quarter + half +quarter);
  noTone (pin);
   tone (pin, f5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, eflat5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, d5);
  delay (eighth);
  noTone (pin);
   tone (pin, d5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, c5);
  delay (eighth);
  noTone (pin);
   tone (pin, d5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, d5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, c5);
  delay (half);
  noTone (pin);
  tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, rest);
  delay (quarter + half +quarter);
  noTone (pin);
   tone (pin, f5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, eflat5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, d5);
  delay (eighth);
  noTone (pin);
   tone (pin, d5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, c5);
  delay (eighth);
  noTone (pin);
   tone (pin, g6);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, d5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, c5);
  delay (half);
  noTone (pin);
  tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, rest);
  delay (quarter + half +quarter);
  noTone (pin);
  tone (pin, f4);
  delay (eighth);
  noTone (pin);
   tone (pin, f5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, eflat5);
  delay (eighth);
  noTone (pin);
   tone (pin, eflat5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, d5);
  delay (eighth);
  noTone (pin);
   tone (pin, d5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, c5);
  delay (eighth);
  noTone (pin);
   tone (pin, bflat5);
  delay (quarter + sixteenth);
  noTone (pin);
   tone (pin, c5);
  delay (eighth);
  noTone (pin);
   tone (pin, c5);
  delay (eighth);
  noTone (pin);
   tone (pin, d5);
  delay (half);
  noTone (pin);
   tone (pin, rest);
  delay (half + eighth);
  noTone (pin);
  tone (pin, c5);
  delay (eighth);
  noTone (pin);
  tone (pin, c5);
  delay (quarter);
  noTone (pin);
  tone (pin, d5);
  delay (half);
  noTone (pin);
  tone (pin, g5);
  delay (dotquarter);
  noTone (pin);
  tone (pin, eflat5);
  delay (dotquarter);
  noTone (pin);
  tone (pin, d5);
  delay (eighth);
  noTone (pin);
  tone (pin, c5);
  delay (eighth);
  noTone (pin);
  tone (pin, rest);
  delay (quarter + half + half);
  noTone (pin);
  tone (pin, bflat6);
  delay (doteighth);
  noTone (pin);
  tone (pin, c6);
  delay (doteighth);
  noTone (pin);
  tone (pin, g5);
  delay (doteighth);
  noTone (pin);
  tone (pin, f5);
  delay (doteighth);
  noTone (pin);
  tone (pin, f5);
  delay (doteighth);
  noTone (pin);
  tone (pin, g5);
  delay (quarter);
  noTone (pin);
  tone (pin, rest);
  delay (quarter + half + half);
  noTone (pin);
  tone (pin, eflat5);
  delay (dotquarter);
  noTone (pin);
  tone (pin, d5);
  delay (dotquarter);
  noTone (pin);
  tone (pin, g5);
  delay (whole + half);
  noTone (pin);
  tone (pin, f5);
  delay (whole + half);
  noTone (pin);
  tone (pin, g5);
  delay (whole + half);
  noTone (pin);
  tone (pin, f5);
  delay (whole + whole);
  noTone (pin);
}
void loop() 
{
  
}
